# Generated by Django 3.2.7 on 2021-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('editora', models.CharField(max_length=150, verbose_name='Editora')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='obras/img', verbose_name='Imagem')),
                ('criado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
            ],
        ),
    ]
